sudo: required
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
branches:
  only:
    - source
script:
  - rm -rf .deploy_git
  - hexo clean
  - hexo generate
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
after_success:
  - git config --local user.name "travis-ci"
  - git config --local user.email "deploy@travis-ci.org"
  - sed -i'' "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy
