sudo: required
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo clean
  - hexo generate
after_success:
  - git config --local user.name "travis-ci"
  - git config --local user.email "deploy@travis-ci.org"
  - sed -i'' "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy
