name: aws deplpy
on:
  push:
    branches:
      - master
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout to master branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: master
      #     fetch-depth: 0
      - name: Upload html to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-east-1"

      - name: Performace test
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"isManual":false,"projectId":1,"caseUrls":[{"value":"https://blog.esunr.xyz/","note":"首页"},{"value":"https://blog.esunr.xyz/2023/04/fbc3f997c608.html","note":"文章详情页"},{"value":"https://blog.esunr.xyz/categories/","note":"文章分类页"}],"reportCount":3,"tags":["online"],"branch":"${{ steps.extract_branch.outputs.branch }}","platform":"desktop","onlyCategories":["performance"],"customerSetting":{}}'
