name: Deploy hexo blog
on:
  push:
    branches:
      - "source"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "source"

      - name: Install node_modules
        uses: borales/actions-yarn@v1.22.18
        with:
          cmd: install
