name: Deploy hexo blog
on:
  push:
    branches:
      - "source"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "source"
      
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: "10"
      
      - name: Setup yarn env & Install node_modules
        uses: borales/actions-yarn@v2.3.0
      
      - name: Check yarn & node version
        run: echo "Node version is `node -v`" && echo "Yarn version is `yarn -v`"
