name: Deploy hexo blog
on:
  push:
    branches:
      - "source"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "source"

      - name: Install node_modules
        uses: borales/actions-yarn@v1.22.18
        with:
          cmd: install

      - uses: actions/setup-node@v3
        with:
          node-version: "10"
        run: echo "Node version is `node -v`" && echo "Yarn version is `yarn -v`"
