name: Deploy hexo blog
on:
  push:
    branches:
      - "source"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "source"

      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "10"

      - name: Setup yarn & Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Check yarn & node version
        run: |
          echo "Node version is `node -v`"
          echo "Yarn version is `yarn -v`"

      - name: Build & Deploy
        run: |
          git config --global user.name "EsunR"
          git config --global user.email "641411169@qq.com"
          git config --global --list
          sed -i'' "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
          rm -rf .deploy_git
          yarn clean
          yarn build
          yarn deploy
