name: Deploy hexo blog
on:
  push:
    branches:
      - "source"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "source"

      - name: Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
        run: echo "Node version is `node -v`" && echo "Yarn version is `yarn -v`"
