name: build
on:
  push:
    branches:
      - source_code
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "source_code"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Setup yarn & Install node_modules
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Check yarn & node version
        run: |
          echo "Node version is `node -v`"
          echo "Yarn version is `yarn -v`"

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      - name: Build & Deploy to github pages
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global --list
          sed -i'' "s~git@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml
          rm -rf .deploy_git
          yarn clean
          yarn build
          yarn deploy
